version: '3.8'
services:
  mysql-node1:
    image: mysql:8.0
    container_name: mysql-node1
    environment:
      MYSQL_ROOT_PASSWORD: root_passdb
      MYSQL_DATABASE: clusterdb
    command: >
      --default-authentication-plugin=mysql_native_password
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --master-info-repository=TABLE
      --relay-log-info-repository=TABLE
      --transaction-write-set-extraction=XXHASH64
      --loose-group_replication_group_name="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      --loose-group_replication_start_on_boot=OFF
      --loose-group_replication_local_address="mysql-node1:33061"
      --loose-group_replication_group_seeds="mysql-node1:33061,mysql-node2:33061,mysql-node3:33061"
      --loose-group_replication_bootstrap_group=ON
    ports:
      - "3306:3306"
    networks:
      - mi-red-cluster-mysql

  mysql-node2:
    image: mysql:8.0
    container_name: mysql-node2
    environment:
      MYSQL_ROOT_PASSWORD: root_passdb
      MYSQL_DATABASE: clusterdb
    command: >
      --default-authentication-plugin=mysql_native_password
      --server-id=2
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --master-info-repository=TABLE
      --relay-log-info-repository=TABLE
      --transaction-write-set-extraction=XXHASH64
      --loose-group_replication_group_name="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      --loose-group_replication_start_on_boot=OFF
      --loose-group_replication_local_address="mysql-node2:33061"
      --loose-group_replication_group_seeds="mysql-node1:33061,mysql-node2:33061,mysql-node3:33061"
    ports:
      - "3307:3306"
    networks:
      - mi-red-cluster-mysql

  mysql-node3:
    image: mysql:8.0
    container_name: mysql-node3
    environment:
      MYSQL_ROOT_PASSWORD: root_passdb
      MYSQL_DATABASE: clusterdb
    command: >
      --default-authentication-plugin=mysql_native_password
      --server-id=3
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --master-info-repository=TABLE
      --relay-log-info-repository=TABLE
      --transaction-write-set-extraction=XXHASH64
      --loose-group_replication_group_name="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      --loose-group_replication_start_on_boot=OFF
      --loose-group_replication_local_address="mysql-node3:33061"
      --loose-group_replication_group_seeds="mysql-node1:33061,mysql-node2:33061,mysql-node3:33061"
    ports:
      - "3308:3306"
    networks:
      - mi-red-cluster-mysql

networks:
  mi-red-cluster-mysql:
    driver: bridge